import Head from "next/head"
import styles from "../styles/Home.module.css"
import { Article, Sentence, Paragraph, Phrase, Right } from "@prisma/client"
import { useEffect } from "react"
import Header from "../components/Header"
import { article, sentence, right } from "../lib/index"

interface FullSentence extends Sentence {
  phrases: Phrase[]
  paragraphs: Paragraph[]
}

export async function getStaticProps() {
  const articles = await article.getAll()
  console.log(articles)

  const sentences = await sentence.getWinners()
  const rights = await right.getAll()
  return {
    props: {
      sentences,
      articles,
      rights,
    },
  }
}

export default function Home({
  articles,
  sentences,
  rights,
}: {
  articles: Article[]
  sentences: FullSentence[]
  rights: Right[]
}) {
  useEffect(() => {
    console.log("Articles: ", articles)
    console.log("Sentences: ", sentences)
  }, [articles, sentences])

  const onClick = () => {
    fetch("http://localhost:3000/api/migrate").then((res) => {
      console.log("Success:", res)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.Hero}>
        <Header />
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>Grundgesätze</h1>
        {/*<button onClick={onClick}>Migrate it!!</button>*/}

        <div className={styles.grid}>
          {sentences.map((sentence) => {
            const right = rights.find((r) => r.id === sentence.rightId)
            return (
              <div key={sentence.id} className={styles.card}>
                <strong>
                  {right?.articlePath} - {right?.text}
                </strong>
                <div key={sentence.id}>{sentence.text}</div>
                <br />
              </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}
