import Head from "next/head"
import styles from "../styles/Home.module.css"
import { Article, Sentence, Paragraph, Phrase, Right } from "@prisma/client"
import { useEffect, useState } from "react"
import Header from "../components/Header"
import { article, sentence, right } from "../lib/index"
import SearchBadge from "../components/SearchBadge"
import SentenceCard from "../components/SentenceCard"

interface FullSentence extends Sentence {
  phrases: Phrase[]
  paragraphs: Paragraph[]
}

export async function getStaticProps() {
  const articles = await article.getAll()
  const sentences = await sentence.getWinners()
  const rights = await right.getAll()
  return {
    props: {
      sentences,
      articles,
      rights,
    },
  }
}

export default function Home({
  articles,
  sentences,
  rights,
}: {
  articles: Article[]
  sentences: FullSentence[]
  rights: Right[]
}) {
  const [search, setSearch] = useState("")

  const searchBadges = [
    "Artikel 1",
    "Menschenwürde",
    "Feminismus",
    "Hautfarbe",
    "Drogen",
    "Freiheit",
    "Krieg",
  ]

  useEffect(() => {
    console.log("Articles: ", articles)
    console.log("Sentences: ", sentences)
  }, [articles, sentences])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.Hero}>
        <div className={styles.content}>
          <Header />
          <h1 className={styles.title}>
            Grundge<span>SÄTZE</span>
          </h1>
          <p className={styles.intro}>
            Im Rahmen des Demokratie-Projektes GrundgeSÄTZE haben über 500
            Schülerinnen deutschlandweit unsere Grundrechte in eigenen Worten
            formuliert.
          </p>

          <div className={styles.Search}>
            <input
              className={styles.searchInput}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              type="text"
              placeholder="z.B. Menschenwürde"
            />
            <div className={styles.searchBadges}>
              {searchBadges.map((text) => (
                <SearchBadge
                  key={text}
                  text={text}
                  active={text === search}
                  onClick={() => setSearch(text)}
                />
              ))}
            </div>
          </div>
        </div>
      </div>

      <main className={styles.winnerSentences}>
        {/*<button onClick={onClick}>Migrate it!!</button>*/}
        <h2>Alle Gewinner-Sätze</h2>
        <div className={styles.grid}>
          {sentences.map((sentence) => {
            const right = rights.find((r) => r.id === sentence.rightId)
            return (
              <SentenceCard
                key={sentence.id}
                articlePath={right?.articlePath ?? ""}
                sentenceText={sentence.text}
                rightText={right?.text ?? ""}
              />
              // <div key={sentence.id} className={styles.card}>
              //   <strong>
              //     {right?.articlePath} - {right?.text}
              //   </strong>
              //   <div key={sentence.id}>{sentence.text}</div>
              //   <br />
              // </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}
